TC_K8S_SERVER_CA="<YOUR SERVER CA FROM ALIYUN CLUSTER>"
TC_K8S_SERVER_URL="<YOUR ADDRESS CA FROM ALIYUN CLUSTER>"
TC_K8S_SSL_EMAIL="<YOUR EMAIL FOR REGISTERING SSL>"
TC_K8S_ADMIN_USER_DASHBOARD="admin-user"



TC_TUT_HELM_REPO_BUCKET="<YOUR_HELM_REPO_BUCKET_SLUG>"
TC_TUT_HELM_REPO_PATH="helm-repo"
TC_TUT_HELM_RAM_USER="tctut-helm-user"
TC_TUT_HELM_RAM_POLICY="tctut-helm-policy"

BASE_APP_DEPLOY_DOMAIN="<YOUR.DOMAIN.COM>"

DOCKER_SECRET_SERVER="registry.<YOUR_GITLAB_DOMAIN>"
DOCKER_SECRET_USER="<DOCKER_PULL_USERNAME>"
DOCKER_SECRET_EMAIL="<DOCKER_PULL_USER_EMAIL>"
DOCKER_SECRET_PASSWORD="<DOCKER_PULL_USER_PASSWORD>"
DOCKER_PULL_SECRET_NAME="regcred"

TC_K8S_GITLAB_DOMAIN_NAME="gitlab.<YOUR_GITLAB_DOMAIN>"
TC_K8S_GITLAB_RUNNER_TOKEN="<RUNNER_TOKEN_FROM_GITLAB_ADMIN_DASH>"
TC_K8S_GITLAB_RUNNER_NAMESPACE="gitlab-runner"





