---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: math-ms
spec:
  replicas: {{ .Values.mathMs.replicaCount }}
  template:
    metadata:
      labels:
        name: math-ms
    spec:
      containers:
      - name: math-ms
        image: {{ .Values.mathMs.image }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 50052
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
      imagePullSecrets:
        - name: {{ .Values.mathMs.imagePullSecret }}