# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import mlservice_pb2 as mlservice__pb2


class MLServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PredictDigit = channel.unary_unary(
        '/ml.MLService/PredictDigit',
        request_serializer=mlservice__pb2.Base64ImageString.SerializeToString,
        response_deserializer=mlservice__pb2.DigitResult.FromString,
        )


class MLServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PredictDigit(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PredictDigit': grpc.unary_unary_rpc_method_handler(
          servicer.PredictDigit,
          request_deserializer=mlservice__pb2.Base64ImageString.FromString,
          response_serializer=mlservice__pb2.DigitResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ml.MLService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
