# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlservice.proto',
  package='ml',
  syntax='proto3',
  serialized_options=_b('\n\023io.grpc.examples.mlB\tMLServiceP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x0fmlservice.proto\x12\x02ml\"\"\n\x11\x42\x61se64ImageString\x12\r\n\x05image\x18\x01 \x01(\t\"\x1d\n\x0b\x44igitResult\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x45\n\tMLService\x12\x38\n\x0cPredictDigit\x12\x15.ml.Base64ImageString\x1a\x0f.ml.DigitResult\"\x00\x42(\n\x13io.grpc.examples.mlB\tMLServiceP\x01\xa2\x02\x03HLWb\x06proto3')
)




_BASE64IMAGESTRING = _descriptor.Descriptor(
  name='Base64ImageString',
  full_name='ml.Base64ImageString',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ml.Base64ImageString.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=57,
)


_DIGITRESULT = _descriptor.Descriptor(
  name='DigitResult',
  full_name='ml.DigitResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ml.DigitResult.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['Base64ImageString'] = _BASE64IMAGESTRING
DESCRIPTOR.message_types_by_name['DigitResult'] = _DIGITRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Base64ImageString = _reflection.GeneratedProtocolMessageType('Base64ImageString', (_message.Message,), dict(
  DESCRIPTOR = _BASE64IMAGESTRING,
  __module__ = 'mlservice_pb2'
  # @@protoc_insertion_point(class_scope:ml.Base64ImageString)
  ))
_sym_db.RegisterMessage(Base64ImageString)

DigitResult = _reflection.GeneratedProtocolMessageType('DigitResult', (_message.Message,), dict(
  DESCRIPTOR = _DIGITRESULT,
  __module__ = 'mlservice_pb2'
  # @@protoc_insertion_point(class_scope:ml.DigitResult)
  ))
_sym_db.RegisterMessage(DigitResult)


DESCRIPTOR._options = None

_MLSERVICE = _descriptor.ServiceDescriptor(
  name='MLService',
  full_name='ml.MLService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=90,
  serialized_end=159,
  methods=[
  _descriptor.MethodDescriptor(
    name='PredictDigit',
    full_name='ml.MLService.PredictDigit',
    index=0,
    containing_service=None,
    input_type=_BASE64IMAGESTRING,
    output_type=_DIGITRESULT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MLSERVICE)

DESCRIPTOR.services_by_name['MLService'] = _MLSERVICE

# @@protoc_insertion_point(module_scope)
